version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    env_file: envfile.txt
    volumes:
      - "/home/adminuser/doc-prac/mysql-vol:/var/lib/mysql"
